[package]
name = "windle"
version = "0.1.0"
edition = "2021"
authors = ["Ote Leo <ote.leo73@gmail.com>"]
description = "Interoperability library for Rust windowing applications."
keywords = ["windowing"]
license = "MIT"


[dependencies]
